name: 'Swarm Upload'
description: 'Upload your dapp to the Swarm decentralized storage'
inputs:
  localRoot:
    description: 'Local folder to upload'
    required: true
  gateway:
    description: 'Swarm Gateway Host'
    required: false
    default: 'https://gateway.ethswarm.org'
  defaultPath:
    description: 'Default path (eg: index.html)'
    required: false
  errorPath:
    description: 'Default path (eg: error.html)'
    required: false
  batchId:
    description: 'Batch Id used to upload data (optional)'
    required: false
    default: '0000000000000000000000000000000000000000000000000000000000000000'
  feedName:
    description: 'Feed topic name (optional)'
    required: false
  feedUserPrivateKey:
    description: 'Feed user (optional / required to update feed)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'white'
